version: '3.8'

services:
  pg_data:
    container_name: pg_data
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tide
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/tide
  
volumes:
  pg_data:
    driver: local